# Generated by Django 5.0.7 on 2024-07-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompraBonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horizonte', models.CharField(max_length=30)),
                ('broker', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=10)),
                ('percio100n', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('tircompra', models.FloatField()),
                ('comision', models.FloatField()),
                ('valororden', models.FloatField()),
                ('valormep', models.FloatField()),
                ('preciooperadousd', models.FloatField()),
                ('comisionusd', models.FloatField()),
                ('valorordenusd', models.FloatField()),
            ],
        ),
    ]
